Update fidget version to v0.3.5 (#117)
* Update fidget version

* Update cargo locked versions due to js-sys conflict (fidget 0.3.5 requires js-sys>0.3.77, but currently locked to 0.3.72)

* Add getrandom backend selection

* Try also enabling the getrandom wasm_js feature

* Try specifying the wasm_js feature at monorepo's level

* Add .cargo/config.toml file with rustflags

* Fix error[E0308]: mismatched types: expected `f32`, found integer

* Rollback: there were other errors otherwise: a value of type `Vec<u8>` cannot be built from an iterator over elements of type `f32`

* Removing possibly redundant config

* Fix type conversion for 3d

---------

Co-authored-by: Steve Genoud <steve@sgenoud.com>